- README.md
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ValidatorTest.java
- src/test/resources/valid-with-relative-ref.json
This change allows to use $id keyword in resource schema, which is necessary to support relative refs to other schemas, which in turn is needed for schema regionalization.
> Allow use of $id keyword in resource schema

- pom.xml
- src/main/java/org/everit/json/schema/PublicJSONPointer.java
- src/main/java/software/amazon/cloudformation/resource/ResourceTypeSchema.java
- src/test/java/org/everit/json/schema/PublicJSONPointerTest.java
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/test-schema.json
- src/test/resources/write-only-model.json
*Description of changes:* Adding some methods to the ResourceSchema class to determine if a given model has writeOnlyProperties and also a method to remove the properties. Tried to make it extensible so that the same thing could be applied to other groups of properties.
I did not handle cases for writeOnlyProperties that were items in arrays, as I was unsure on if this was allowed or what the behavior should be. Say, if "/properties/arrayProperty/0" is writeOnly, and the array has two items, if we remove one, then the object still appears to have a writeOnlyProperty after removal:
```
{
"arrayProperty": [0, 1]
}
```
After:
```
{
"arrayProperty": [1] //still has item at "/properties/arrayProperty/0"
}
```
Input on this would be great.
By submitting this pull …
> Adding methods to remove writeOnlyProperties from model

- .travis.yml
*Issue #, if available:* #69 
*Description of changes:* Travis have recently updated their base image of bionic (Tue Dec 17 14:57:15 UTC 2019). Unfortunately, this has also changed the pre-baked Python versions from:
```bash
$ pyenv versions
* system (set by /opt/pyenv/version)
2.7.15
3.6.7
3.7.1
```
to:
```bash
$ pyenv versions
* system (set by /opt/pyenv/version)
2.7
2.7.17
3.6
3.6.9
3.7
3.7.5
3.8
3.8.0
```
I think this is still an easy solution, the alternative was something like:
```bash
$ pyenv versions | grep '3.8' | sort -nr | head -n1 | xargs pyenv local
```
> Set new pyenv version

- pom.xml
*Description of changes:* Bumping version so I can have an updated dependency to make changes in the java plugin related to #64. I removed the scm tag as we don't need the tag [(rpdk java library does not have it)](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/pom.xml#L34). Becomes one less thing to worry about updating.
> Bumping version

- README.md
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ValidatorTest.java
This adds a new parameter `timeoutInMinutes` to the `handlerDefinition`, in order for providers to specify a custom stabilization timeout, to be used by CloudFormation. This could be used by the handler itself at some point to stop doing work.
I used `timeoutInMinutes` since it is much simpler for handlers rather than specifying some ISO format, and I don't see any need to have any more granularity than that
> add custom stabilization timeout in handlers schema

- src/main/resources/examples/resource/initech.tps.report.v1.json
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ValidatorTest.java
*Issue #, if available:* #62 
*Description of changes:* Allow resource authors to attach template links to the schema that consumers of the schema/resources can use to generate links directly to the resource. An example might be EC2. The console link is:
```
https://eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#Instances:instanceId=i-xxxxxx
```
In this case, the service link might look like this:
```
"serviceLink": {
"templateUri": "/ec2/home?region=${awsRegion}#Instances:instanceId=${instanceId}",
"mappings": {
"instanceId": "/InstanceId"
}
},
```
Where `awsRegion` is a "global" variable (so far, the only one), and `instanceId` is a variable defined via a JSON pointer to a property *in a resource blob* (returned by e.g. READ) and not in the schema. The relative URI is …
> Service Link

- src/main/java/software/amazon/cloudformation/resource/Validator.java
I have a use case where a consumer of this package would like to run schema validation tests without opening an internet connection. Making Validator(SchemaClient downloader) public enables this use case - I can inject a mock SchemaClient and avoid mocking an entire HTTP server
> Make ctor Validator(SchemaClient downloader) public

- README.md
The example about references in the readme mentions a property called `Name` in AWS::EC2::VPC which doesn't exist in that schema. That is a bit confusing, so I would like to change it to `Id`.
> Readme: Fix example about references

- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ValidatorTest.java
* As we launched resource registry platform v2, the timeout limit has increased from 12 hrs to 36 hrs. Hence, we also need to increase **timeoutInMinutes** from 720 to 2160 (36 x 60) 
> Increase timeoutInMinutes from 720 to 2160

- src/main/java/software/amazon/cloudformation/resource/ResourceTypeSchema.java
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/valid-with-allof-schema.json
- src/test/resources/valid-with-anyof-schema.json
When the schema contains a [combining property](https://json-schema.org/understanding-json-schema/reference/combining.html) such as "oneOf", GetAtt calls fail with the error message "Requested attribute **[attribute]** does not exist in schema for **[typeName]**".
This PR fixes the issue by changing ResourceTypeSchema's definesProperty method.
- minimal schema, schema with oneOf, schema with anyOf, schema with allOf
- checks that definesProperty correctly returns true or false depending on the whether the property exists
> Fixed GetAtt when combining property is in schema

- src/main/resources/schema/provider.definition.schema.v1.json
*Issue #, if available:* N/A
*Description of changes:* Default set a string of a boolean for taggable
> Fix default taggable to boolean instead of string

- .github/workflows/maven-release.yml
- pom.xml
*Description of changes:* This PR automates releases to our maven staging repo. Similar to https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/339
This release workflow uses the official java github action to set up the necessary credentials, and the deploy stage executes the command.
> Add release job to staging repo

- src/main/java/software/amazon/cloudformation/resource/ResourceTypeSchema.java
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/test-schema.json
*Issue #, if available:* https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/issues/30
Adding `conditionallyCreateOnlyProperties` to meta schema, so that resource providers could model properties that could not deterministically predict replacement/inline update
> Adding conditionallyCreateOnlyProperties to metaschema

- src/main/java/software/amazon/cloudformation/resource/ResourceTypeSchema.java
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/valid-with-update-handler-schema.json
https://github.com/aws-cloudformation/cloudformation-resource-schema/pull/105#discussion_r634834873
As discussed with @PatMyron offline, we need to set the default value of taggable to be false when UpdateHandler is not provided, so that update on stack level tags won't trigger the replace update of the resource.
> Set default taggable to false when UpdateHandler not provided

- pom.xml
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/test-schema-with-hidden-pointers.json
- src/test/resources/test-schema-with-invalid-hidden-pointers.json
Add nonPublicProperties and nonPublicDefinitions lists of JSONPointers in metaschema. Adding top level lists to allow hidden
property and definition paths to be accepted. Also update lombok version as it fails local build.
> Add nonPublicProperties and nonPublicDefinitions lists of JSONPointers

- src/main/java/software/amazon/cloudformation/resource/ResourceTypeSchema.java
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
Change the removeProperty function to catch NullPointerException, as this implies the parent object was null when removing a nested property. This function is intended to take no action when the property to be removed was null, so it should take no action in this case as well.
> fix a NPE with nested writeOnlyProperties with optional parent.

- README.md
*Description of changes:* Update `README` with `tagging` metadata key description and examples
> Update README with 'tagging' metadata key description

- README.md
- src/main/resources/schema/base.definition.schema.v1.json
- src/test/resources/invalid-update-tagging-schema.json
- src/test/resources/test-schema.json
- src/test/resources/valid-with-tagging-schema.json
arrayType is only applicable for property of type array. When set to AttributeList, it indicates that the array is of nested type objects, and when set to Standard it indicates that the array consists of primitive types.
> Add custom tag arrayType

- README.md
- pom.xml
This version is also available through maven central. The group id changed but that is the one to use according to the homepage https://github.com/everit-org/json-schema
*Issue #, if available:* not available
Just bumped one of the dependencies. The main benefit is that now all dependencies are available on maven central.
> Bump everit-json-schema version

- src/main/java/software/amazon/cloudformation/resource/ResourceTagging.java
- src/main/java/software/amazon/cloudformation/resource/ResourceTypeSchema.java
- src/main/resources/schema/provider.definition.schema.v1.json
- src/test/java/software/amazon/cloudformation/resource/ResourceTaggingTest.java
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/valid-with-tagging-schema.json
Add permissions field in tagging schema to specify permissions needed for tags.
Add unit test for permissions field.
> Add permissions to tagging schema

- src/main/java/software/amazon/cloudformation/resource/ResourceTagging.java
- src/test/java/software/amazon/cloudformation/resource/ResourceTypeSchemaTest.java
- src/test/resources/invalid-with-tagging-bad-pointer-schema.json
- src/test/resources/invalid-with-tagging-bad-reference-schema.json
- src/test/resources/valid-with-tagging-missing-tagProperty-schema.json
- src/test/resources/valid-with-tagging-nested-property-schema.json
This code change enhances validation of the `tagProperty`.
1. Validates if there is a correct pointer specified
2. Validates if reference uses correct notation (must start with `/properties/`)
3. Allows tags to be nested properties.
> Allowed Nested reference for TagProperty
